version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpressVolume:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context : ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PW: ${DB_USER_PW}
        DB_ROOT_PW: ${DB_ROOT_PW}
    env_file:
      - .env
    volumes:
      - mariadbVolume:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpressVolume:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadbVolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abelqasm/data/mariadbVolume
  wordpressVolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abelqasm/data/wordpressVolume

networks:
  inception:
    driver: bridge