version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - wordpressVolume:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context : ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PW: ${DB_USER_PW}
        DB_ROOT_PW: ${DB_ROOT_PW}
    env_file:
      - .env
    volumes:
      - mariadbVolume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpressVolume:/var/www/html
    restart: always

volumes:
  mariadbVolume: 
  wordpressVolume: 